# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthWindow.sizePolicy().hasHeightForWidth())
        AuthWindow.setSizePolicy(sizePolicy)
        AuthWindow.setMinimumSize(QtCore.QSize(1000, 700))
        AuthWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons8-отмеченный-чекбокс-100 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AuthWindow.setWindowIcon(icon)
        AuthWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-1, -1, 1005, 705))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.groupBox.setFont(font)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #35155d, stop:0.33 #512b81, stop:1 #a26985);\n"
" ")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_log = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_log.setGeometry(QtCore.QRect(200, 250, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.lineEdit_log.setFont(font)
        self.lineEdit_log.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255, 150);")
        self.lineEdit_log.setFrame(False)
        self.lineEdit_log.setObjectName("lineEdit_log")
        self.pushButton_signin = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_signin.setGeometry(QtCore.QRect(200, 390, 295, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.pushButton_signin.setFont(font)
        self.pushButton_signin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_signin.setStyleSheet("\n"
"QPushButton {\n"
"background-color: rgb(0, 0, 0, 50); \n"
"color: rgb(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgb(0, 0, 0, 70); \n"
"color: rgb(255, 255, 255, 90);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(0, 0, 0, 90); \n"
"color: rgb(255, 255, 255, 90);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_signin.setObjectName("pushButton_signin")
        self.pushButton_reg = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reg.setGeometry(QtCore.QRect(505, 390, 295, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reg.setStyleSheet("\n"
"QPushButton {\n"
"background-color: rgb(0, 0, 0, 50); \n"
"color: rgb(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgb(0, 0, 0, 70); \n"
"color: rgb(255, 255, 255, 90);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(0, 0, 0, 90); \n"
"color: rgb(255, 255, 255, 90);\n"
"}")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.lineEdit_passw = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_passw.setGeometry(QtCore.QRect(200, 320, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.lineEdit_passw.setFont(font)
        self.lineEdit_passw.setStyleSheet("\n"
"\n"
"/*border-color: rgb(0, 0, 0);\n"
"border: 2px solid;*/\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255, 150);")
        self.lineEdit_passw.setFrame(False)
        self.lineEdit_passw.setObjectName("lineEdit_passw")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(1103, 40, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"background-color: rgb(255, 255, 255, 0);\n"
"    color: rgb(0, 0, 0, 150);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"/*width: 65px;\n"
"height: 65px;*/\n"
"width: 40px;\n"
"height: 40px;\n"
"/*border-image: url(:/icon/resourses/icons8-unchecked-checkbox-100.png);*/\n"
"    border-image: url(:/icon/resourses/free-icon-exclamation-5022900.png);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"width: 65px;\n"
"height: 65px;\n"
"border-image: url(:/icon/resourses/icons8-checked-checkbox-100.png) /*url(:/icon/resourses/icon2.png);*/\n"
"}")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(200, 70, 600, 161))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255, 150);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "ToDo Tools"))
        self.lineEdit_log.setPlaceholderText(_translate("AuthWindow", "Введите логин"))
        self.pushButton_signin.setText(_translate("AuthWindow", "Войти"))
        self.pushButton_reg.setText(_translate("AuthWindow", "Регистрация"))
        self.lineEdit_passw.setPlaceholderText(_translate("AuthWindow", "Введите пароль"))
        self.label.setText(_translate("AuthWindow", "ToDo Tools"))
import res5


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthWindow = QtWidgets.QMainWindow()
    ui = Ui_AuthWindow()
    ui.setupUi(AuthWindow)
    AuthWindow.show()
    sys.exit(app.exec_())
