# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(1060, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HelpWindow.sizePolicy().hasHeightForWidth())
        HelpWindow.setSizePolicy(sizePolicy)
        HelpWindow.setMinimumSize(QtCore.QSize(1060, 740))
        HelpWindow.setMaximumSize(QtCore.QSize(1060, 740))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons8-отмеченный-чекбокс-100 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HelpWindow.setWindowIcon(icon)
        HelpWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(HelpWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-1, -1, 1062, 945))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.groupBox.setFont(font)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #35155d, stop:0.33 #512b81, stop:1 #a26985);\n"
" ")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 9, 1021, 721))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255, 130);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setObjectName("plainTextEdit")
        HelpWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "Help!"))
        self.plainTextEdit.setPlainText(_translate("HelpWindow", "---- Как создать новую задачу? ----\n"
"  Для этого необходимо ввести текст задачи в поле \"Введите текст\". Если задача имеет крайний срок выполнения - введите дату в поле \"01/01/2001\". Если эта задача является важной - выберете значок 🔥 справа от полей ввода.\n"
"  После заполнения всех полей нажмите кнопку \"Сохранить\".\n"
"---- Что означают кнопки в строке рядом с моей задачей? ----\n"
"  Галочка слева от текста задачи указывает, выполнена она или нет.\n"
"  🔥 справа от текста задачи означает, что она помечена важной к выполнению (или же не помечена).\n"
"  Дата справа от 🔥 - крайний срок выполнения задачи.\n"
"  Мусорная корзина - по этой кнопке можно удалить соответствующую задачу.\n"
"---- Что за 🔥? ---- \n"
"  Он означает, что эта задача находится в категории важных.\n"
"---- Как отредактировать информацию о моей задаче? ----   \n"
"  Чтобы изменить состояние выполнения задачи - нажмите на галочку.\n"
"  Чтобы изменить текст задачи - два раза кликните на нём, измените текст, а затем нажмите Enter.\n"
"  Чтобы изменить статус важности задачи - нажмите на 🔥.\n"
"  Чтобы изменить крайний срок выполнения - два раза нажмите на него, измените, а затем нажмите Enter.\n"
"---- Как найти нужную мне задачу? ----\n"
"  Если вам нужно найти задачу по её формулировке - введите соответствующий текст в поле \"Введите текст\". Если же по конкретной дате крайнего срока - введите её в поле \"01/01/2001\". Можно найти задачу по одному или по двум этим критериям сразу.\n"
"  После заполнения полей нажмите кнопку \"Найти\".\n"
"  Или можете поискать задачу, отфильтровав задачи по кнопкам \"Все\", \"Незавершённые\" и т.д.\n"
"---- Что означают кнопки \"Все\", \"Незавершённые\" и т.д.? ----\n"
"  \"Все\" - эта кнопка выводит все созданные пользователем записи.\n"
"  \"Незавершённые\" - выводит задачи, у которых не стоит галочка в их выполнении.\n"
"  \"Просроченные\" - выводит задачи, срок выполнения которых истёк и они не были выполнены.\n"
"  \"Завершённые\" - выводит задачи, которые уже были выполнены.\n"
"  \"Важные\" - выводит все задачи, помеченные 🔥.\n"
"  \"Близжайшие\" - выводит все задачи, крайний срок которых сегодня или завтра.\n"
"---- Как удалить задачу? ----\n"
"  Нажмите на мусорную корзину рядом с ней.\n"
"---- Как выйти из моей учётной записи? ----\n"
"  Нажмите на кнопку \"Выйти\" рядом с кнопкой \"Помощь\"."))
import res5


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpWindow = QtWidgets.QMainWindow()
    ui = Ui_HelpWindow()
    ui.setupUi(HelpWindow)
    HelpWindow.show()
    sys.exit(app.exec_())
