# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'but.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttWindow(object):
    def setupUi(self, AttWindow):
        AttWindow.setObjectName("AttWindow")
        AttWindow.resize(400, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons8-отмеченный-чекбокс-100 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AttWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AttWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-1, -1, 405, 205))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #35155d, stop:0.33 #512b81, stop:1 #a26985);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_ok = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ok.setGeometry(QtCore.QRect(300, 150, 90, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("\n"
"QPushButton {\n"
"background-color: rgb(0, 0, 0, 40); \n"
"color: rgb(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgb(0, 0, 0, 60); \n"
"color: rgb(255, 255, 255, 90);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(0, 0, 0, 80); \n"
"color: rgb(255, 255, 255, 90);\n"
"}")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label_text = QtWidgets.QLabel(self.groupBox)
        self.label_text.setGeometry(QtCore.QRect(25, 20, 350, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_text.sizePolicy().hasHeightForWidth())
        self.label_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255, 150);")
        self.label_text.setText("")
        self.label_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_text.setWordWrap(True)
        self.label_text.setObjectName("label_text")
        AttWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AttWindow)
        QtCore.QMetaObject.connectSlotsByName(AttWindow)

    def retranslateUi(self, AttWindow):
        _translate = QtCore.QCoreApplication.translate
        AttWindow.setWindowTitle(_translate("AttWindow", "Attention!"))
        self.pushButton_ok.setText(_translate("AttWindow", "ОК"))
import res5


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttWindow = QtWidgets.QMainWindow()
    ui = Ui_AttWindow()
    ui.setupUi(AttWindow)
    AttWindow.show()
    sys.exit(app.exec_())
