# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1560, 940)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1560, 940))
        MainWindow.setMaximumSize(QtCore.QSize(1560, 940))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons8-отмеченный-чекбокс-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-1, -1, 1565, 945))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.groupBox.setFont(font)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #35155d, stop:0.33 #512b81, stop:1 #a26985);\n"
" ")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 820, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
# "background-color: rgba(255, 255, 255, 150);")
"background-color: rgba(255, 255, 255, 0.6);")

        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(1180, 70, 170, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 40); \n"
"color: rgba(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(0, 0, 0, 60); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 0, 0, 80); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(1360, 70, 170, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 40); \n"
"color: rgba(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(0, 0, 0, 60); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 0, 0, 80); \n"
"color: rgba(255, 255, 255, 90);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(870, 70, 220, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 150);")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(1107, 57, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(0, 0, 0, 150);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"width: 55px;\n"
"height: 55px;\n"
"border-image: url(:/icon/icons8-fire-80 (1).png);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"width: 55px;\n"
"height: 55px;\n"
"border-image: url(:/icon/icons8-fire-80 (3).png);\n"
"}")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(42, 210, 1480, 651))
        self.tableWidget.setStyleSheet("QTableWidget{font: 16pt \"Comic Sans MS\";background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 130);\n"
"gridline-color: transparent;\n"
"border-radius: 10px;}\n"
"QTableWidget::item {border: none;}")
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.label_time = QtWidgets.QLabel(self.groupBox)
        self.label_time.setGeometry(QtCore.QRect(1159, 10, 351, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"\n"
"")
        self.label_time.setText("")
        self.label_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 140, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {background-color: rgba(a255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"border: 2px solid rgba(255, 255, 255, 110);}\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 50);}\n"
"QPushButton:pressed {background-color: rgba(255, 255, 255, 0); color: white; border: 2px solid white;}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 140, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"border: 2px solid rgba(255, 255, 255, 110);}\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 50);}\n"
"QPushButton:pressed {background-color: rgba(255, 255, 255, 0); color: white; border: 2px solid white;}\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(780, 140, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"border: 2px solid rgba(255, 255, 255, 110);}\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 50);}\n"
"QPushButton:pressed {background-color: rgba(255, 255, 255, 0); color: white; border: 2px solid white;}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(1030, 140, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"border: 2px solid rgba(255, 255, 255, 110);}\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 50);}\n"
"QPushButton:pressed {background-color: rgba(255, 255, 255, 0); color: white; border: 2px solid white;}\n"
"\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(1280, 140, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"border: 2px solid rgba(255, 255, 255, 110);}\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 50);}\n"
"QPushButton:pressed {background-color: rgba(255, 255, 255, 0); color: white; border: 2px solid white;}\n"
"\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 140, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setMouseTracking(False)
        self.pushButton_4.setStyleSheet("QPushButton {background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"border: 2px solid rgba(255, 255, 255, 110);}\n"
"QPushButton::hover {\n"
"background-color: rgba(255, 255, 255, 50);}\n"
"QPushButton:pressed {background-color: rgba(255, 255, 255, 0); color: white; border: 2px solid white;}\n"
"\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_help = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_help.setGeometry(QtCore.QRect(1340, 880, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_help.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 40); \n"
"color: rgba(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(0, 0, 0, 60); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 0, 0, 80); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_help.setObjectName("pushButton_help")
        self.label_name = QtWidgets.QLabel(self.groupBox)
        self.label_name.setGeometry(QtCore.QRect(50, 10, 1011, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(255, 255, 255, 110);\n"
"\n"
"\n"
"\n"
"")
        self.label_name.setText("")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.pushButton_exit = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_exit.setGeometry(QtCore.QRect(1450, 880, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 40); \n"
"color: rgba(255, 255, 255, 90);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(0, 0, 0, 60); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 0, 0, 80); \n"
"color: rgba(255, 255, 255, 90);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo Tools"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введите текст"))
        self.pushButton_7.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_8.setText(_translate("MainWindow", "Найти"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "01/01/2001"))
        self.pushButton_2.setText(_translate("MainWindow", "Незавершённые"))
        self.pushButton_6.setText(_translate("MainWindow", "Просроченные"))
        self.pushButton_3.setText(_translate("MainWindow", "Завершённые"))
        self.pushButton_5.setText(_translate("MainWindow", "Важные"))
        self.pushButton_9.setText(_translate("MainWindow", "Близжайшие"))
        self.pushButton_4.setText(_translate("MainWindow", "Все"))
        self.pushButton_help.setText(_translate("MainWindow", "Помощь"))
        self.pushButton_exit.setText(_translate("MainWindow", "Выход"))
import res5


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
